variable "name" {}
variable "rg-name" {}
variable "rg-location" {}
variable "allocation_method" {}
variable "subnet_ids" {}
variable "source_file_path" {}
variable "destination_file_path" {}
variable "admin_username" {}
variable "admin_password" {}